Improve performance of chunk saving
TerraFirmaCraft-The-Final-Frontier/RoughlyEnoughIDs pull request #64
Opened 2024-07-10 15:13 UTC by hohserg1

We have some frequently used logic at https://github.com/TerraFirmaCraft-The-Final-Frontier/RoughlyEnoughIDs/blob/master/src/main/java/org/dimdev/jeid/mixin/core/world/MixinBlockStateContainer.java#L60-L64
that uses IBlockState as a key of HashMap, so this pr about caching of IBlockState#hashCode to not compute a same value multiple times.
Also, the second commit aims to fix hashCode collisions by considering a block instance instead of only properties for hashCode of IBlockState

2024-07-10 20:51 UTC, jchung01 requested changes
Just a couple changes needed, mainly the objects used for hashing is incorrect. ~~I would also appreciate a comparison in memory usage in a decent-sized modpack to make sure this doesn't use a lot of memory considering we are adding an extra field to every blockstate, which there are about 10k of just in vanilla.~~ Actually I suppose it's just 1 field, considering other mods like VintageFix add more than that it should be fine.

2024-07-10 20:51 UTC, jchung01 commented on src/main/java/org/dimdev/jeid/mixin/core/world/MixinStateImplementation.java
> +import org.spongepowered.asm.mixin.injection.callback.*;
Please avoid using wildcard imports

2024-07-10 20:51 UTC, jchung01 commented on src/main/java/org/dimdev/jeid/mixin/core/world/MixinStateImplementation.java
> +    private int hashCodeValue;
Use `@Unique` annotation

2024-07-10 20:51 UTC, jchung01 commented on src/main/java/org/dimdev/jeid/mixin/core/world/MixinStateImplementation.java
> +    private ImmutableMap<IProperty<?>, Comparable<?>> properties;
Should have `@Final` annotation as `properties` is a final variable

2024-07-10 20:51 UTC, jchung01 commented on src/main/java/org/dimdev/jeid/mixin/core/world/MixinStateImplementation.java
> +        hashCodeValue = Objects.hash(this, properties);
Using `this` in the hash is incorrect; this is a mixin so `this` would just call this mixin's `hashCode() -> hashCodeValue -> 0`. I think you meant to shadow `StateImplementation#block` and use that as part of the hash?

2024-07-10 21:11 UTC, jchung01 commented
Actually, is it even necessary to generate the hashcode ourselves? Every state should be unique, so using the default `hashCode()` implementation of `Object` should be enough, and eliminates the expensive operation of hashing the map. VintageFix actually already does [this](https://github.com/embeddedt/VintageFix/blob/a4625526fd1a19336fd9424551b6519e5f81110d/src/main/java/org/embeddedt/vintagefix/mixin/blockstates/FastMapStateHolderMixin.java#L104-L111), so the most we would need to do is copy their hashcode method in case the user isn't using VintageFix with REID.

2024-07-11 12:26 UTC, hohserg1 commented
ty for review!
yeah, bc of every blockstate is singleton, have sense to use default `hashCode()`.
VintageFix are calling `identityHashCode` every time when hashCode required, but javadoc meaning it is not just returning value, its kinda calculated every time.
![image](https://github.com/TerraFirmaCraft-The-Final-Frontier/RoughlyEnoughIDs/assets/35610168/87e5a9f5-119f-4963-b620-d4b186807228)
Also VintageFix are using `this`. Is it meaning `this` at `@Overwrite` pointing to `this` of target class instance, but `this` at `@Inject` pointing to mixin's `this`?

2024-07-11 18:39 UTC, jchung01 commented
Yes, `System#identityHashCode` does do some calculation for the hash code, but relatively speaking, it is only "expensive" when calculating the hash code for the first time on an object - in this case, that's sometime during game load, which is fine. Following calls are cheap (see [here](https://shipilev.net/jvm/anatomy-quarks/26-identity-hash-code/#_hashcode_generators_performance)). So I would say VintageFix's decision to use it is correct, and it is what we should use in this mixin. In fact, this PR/mixin may not be necessary, because this is a general optimization that VintageFix already does, and it seems unlikely a user would have REID but not VintageFix. However, if you want to copy VintageFix's hashCode impl to this mod for redundancy, go ahead and make the changes.

> Also VintageFix are using this. Is it meaning this at @Overwrite is pointing to this of target class instance, but this at @Inject is pointing to mixin's this?

Normally, to reference the actual `this` of the mixin target's class, you would (in this case) cast like `((StateImplementation) (Object) this)`, but `identityHashCode()` just needs the `Object`, so any casting is redundant.

2024-07-20 08:30 UTC, closed without merging